# Day 2: Numpy and Pandas
## Author: Kush Mehta

In [6]:
# Import packages
import numpy as np
import pandas as pd

### Numpy: 
#### Do scientific Computing

In [8]:
# Null Vector of size 10 but 4th value is 1
V1 = np.zeros(10)
V1[3] = 1
print(V1)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [14]:
# Vector with values from 10 to 20 
V2 = np.arange(10,21)
print(V2)

[10 11 12 13 14 15 16 17 18 19 20]


In [18]:
# Reverse the Vector above
V3 = V2[::-1]
print(V3)

[20 19 18 17 16 15 14 13 12 11 10]


In [174]:
# Random Vector of size 30, sort it and find average
V4 = np.random.random(30)
V4.sort()
print(V4)
V4.mean()

[0.04039565 0.06036297 0.10019378 0.1042726  0.34911077 0.35021059
 0.42364649 0.44303201 0.4447893  0.44998696 0.47131859 0.47875823
 0.57851849 0.583725   0.63386002 0.68298097 0.70612958 0.72860653
 0.7514068  0.7597444  0.76007453 0.76043558 0.76184117 0.85261021
 0.94002033 0.94630533 0.95638592 0.96079614 0.97551327 0.98355971]


0.6012863970130305

### Pandas
- Manipulate data in Python 

In [180]:
# Create a data frame from a table
# Create sex variable 
## Array to store sex values
sex = np.array(['Male','Female'])
# Repeat 10 times
sex_vec = np.repeat(sex,10)
sex_vec # Check

array(['Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male', 'Male',
       'Male', 'Male', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Female', 'Female', 'Female'], dtype='<U6')

In [188]:
# Create method variable
## Array to store method values
method = np.array(['Electric','Nice'])
# Repeat 5 times 
method_v = np.repeat(method,5)
method_v # Check
## Repeat twice for both samples
method_vec = np.tile(method_v,2)
method_vec # Check

array(['Electric', 'Electric', 'Electric', 'Electric', 'Electric', 'Nice',
       'Nice', 'Nice', 'Nice', 'Nice', 'Electric', 'Electric', 'Electric',
       'Electric', 'Electric', 'Nice', 'Nice', 'Nice', 'Nice', 'Nice'],
      dtype='<U8')

In [192]:
# Create score variable 
score = np.array([15,14,29,13,13,
                  10,9,8,8,7,
                  6,7,5,4,8,
                  12,10,7,8,13])

In [194]:
# Combine variables into data frame 
df_reinf = pd.DataFrame({'Sex': sex_vec, 'Method': method_vec, 'Score': score})
print(df_reinf)

       Sex    Method  Score
0     Male  Electric     15
1     Male  Electric     14
2     Male  Electric     29
3     Male  Electric     13
4     Male  Electric     13
5     Male      Nice     10
6     Male      Nice      9
7     Male      Nice      8
8     Male      Nice      8
9     Male      Nice      7
10  Female  Electric      6
11  Female  Electric      7
12  Female  Electric      5
13  Female  Electric      4
14  Female  Electric      8
15  Female      Nice     12
16  Female      Nice     10
17  Female      Nice      7
18  Female      Nice      8
19  Female      Nice     13


### Browse data with iloc and loc
- iloc: position-based
- loc: label-based

In [198]:
# View the first 10 rows with iloc
# iloc[rows,columns]
df_reinf.iloc[0:10,:]


Sex    Method  Score
0  Male  Electric     15
1  Male  Electric     14
2  Male  Electric     29
3  Male  Electric     13
4  Male  Electric     13
5  Male      Nice     10
6  Male      Nice      9
7  Male      Nice      8
8  Male      Nice      8
9  Male      Nice      7

In [204]:
# View last 10 rows for "Sex" and "Score" using loc
df_reinf.loc[10:20,('Sex','Score')]

Sex  Score
10  Female      6
11  Female      7
12  Female      5
13  Female      4
14  Female      8
15  Female     12
16  Female     10
17  Female      7
18  Female      8
19  Female     13